stages:
  - build
  - test
  - sonarqube-check
  - sonarqube-vulnerability-report

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - local: ".gitlab/ci/*.gitlab-ci.yml"
