name: animal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.13
  - pip=23.0.1
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - deeplabcut==2.3.8
      - gradio==4.7.1
      - ipython==8.18.1
      - scikit-learn==1.3.2
      - tensorflow==2.11.1
      - torch==1.12.0+cu113
      - torchaudio==0.12.0+cu113
      - torchvision==0.13.0+cu113
      - ultralytics==8.0.222
